name: Autogenerate SDK (Claude) and Create PR

on:
  push:
    branches:
      - main
    paths:
      - exa-js/old_openapi.yaml
      - exa-js/new_openapi.yaml
  workflow_dispatch:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use the Python version your project requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run autogen_sdk to update index.ts
        run: |
          python autogen_sdk_claude.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Auto-generate SDK and update index.ts'
          title: 'Auto-generate SDK and update index.ts'
          body: 'This PR contains the updated `index.ts` file based on changes in `old_openapi.yaml` and `new_openapi.yaml`.'
          branch: 'auto-generate-sdk'
          labels: 'autogen, sdk'
